package main

// Code generated by gowrap. DO NOT EDIT.
// template: template/zap
// gowrap: http://github.com/hexdigest/gowrap

//go:generate gowrap gen -p lesson1 -i Page -t template/zap -o loggerPageZapWrap.go -l ""

import (
	"go.uber.org/zap"
)

type loggerPageWrap struct {
	logger *zap.SugaredLogger
	base   Page
}

func NewloggerPageWrap(base Page, log *zap.SugaredLogger) loggerPageWrap {
	return loggerPageWrap{
		base:   base,
		logger: log,
	}
}

func (d loggerPageWrap) GetLinks() (sa1 []string) {
	d.logger.Debug("Call Page -> GetLinks() (sa1 []string)")
	res := d.base.GetLinks()
	d.logger.Debugf("Result GetLinks: %v", res)
	return res
}

func (d loggerPageWrap) GetTitle() (s1 string) {
	d.logger.Debug("Call Page -> GetTitle() (s1 string)")
	res := d.base.GetTitle()
	d.logger.Debugf("Result GetTitle: %v", res)
	return res
}
