package main

// Code generated by gowrap. DO NOT EDIT.
// template: template/zap
// gowrap: http://github.com/hexdigest/gowrap

//go:generate gowrap gen -p lesson1 -i Crawler -t template/zap -o loggerCrawlerZapWrap.go -l ""

import (
	"context"

	"go.uber.org/zap"
)

type loggerCrawlerWrap struct {
	logger *zap.SugaredLogger
	base   Crawler
}

func NewloggerCrawlerWrap(base Crawler, log *zap.SugaredLogger) loggerCrawlerWrap {
	return loggerCrawlerWrap{
		base:   base,
		logger: log,
	}
}

func (d loggerCrawlerWrap) AddDepth() {
	d.logger.Debug("Call Crawler -> AddDepth() ()")
	d.base.AddDepth()

}

func (d loggerCrawlerWrap) ChanResult() (ch1 <-chan CrawlResult) {
	d.logger.Debug("Call Crawler -> ChanResult() (ch1 <-chan CrawlResult)")
	res := d.base.ChanResult()
	d.logger.Debugf("Result ChanResult: %v", res)
	return res
}

func (d loggerCrawlerWrap) Scan(ctx context.Context, url string, inc int64) {
	d.logger.Debug("Call Crawler -> Scan(ctx context.Context, url string, inc int64) ()")
	d.base.Scan(ctx, url, inc)

}
