package loggerDebugWrap

// Code generated by gowrap. DO NOT EDIT.
// template: ../../template/zap
// gowrap: http://github.com/hexdigest/gowrap

//go:generate gowrap gen -p lesson1/internal/page -i Page -t ../../template/zap -o loggerPageZapWrap.go -l ""

import (
	"lesson1/internal/page"

	"go.uber.org/zap"
)

type loggerPageWrap struct {
	logger *zap.SugaredLogger
	base   page.Page
}

func NewloggerPageWrap(base page.Page, log *zap.SugaredLogger) loggerPageWrap {
	return loggerPageWrap{
		base:   base,
		logger: log,
	}
}

func (d loggerPageWrap) GetLinks() (sa1 []string) {
	d.logger.Debug("Call page.Page -> GetLinks() (sa1 []string)")
	res := d.base.GetLinks()
	d.logger.Debugf("Result GetLinks: %v", res)
	return res
}

func (d loggerPageWrap) GetTitle() (s1 string) {
	d.logger.Debug("Call page.Page -> GetTitle() (s1 string)")
	res := d.base.GetTitle()
	d.logger.Debugf("Result GetTitle: %v", res)
	return res
}
